apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-boot-app-2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-boot-app-2
  template:
    metadata:
      labels:
        app: spring-boot-app-2
    spec:
      containers:
      - name: app
        image: ghcr.io/szabobalazs2003/spring-boot-k8s-2:latest
        ports:
        - containerPort: 8081
