apiVersion: networking.istio.io/v1
kind: Gateway
metadata:
  name: ingress-gateway
  namespace: istio-system
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "*"

---

apiVersion: networking.istio.io/v1
kind: VirtualService
metadata:
  name: spring-boot-app-2
  namespace: app2
spec:
  hosts:
  - spring-boot-app-2.app2.svc.cluster.local
  gateways:
  - istio-system/ingress-gateway
  http:
    route:
    - destination:
        host: spring-boot-app-2.app2.svc.cluster.local
        port:
          number: 8000

---

apiVersion: networking.istio.io/v1
kind: DestinationRule
metadata:
  name: spring-boot-app-2
spec:
  host: spring-boot-app-2.app2.svc.cluster.local