apiVersion: networking.istio.io/v1
kind: Gateway
metadata:
  name: ingress-gateway
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "*"

---

apiVersion: networking.istio.io/v1
kind: VirtualService
metadata:
  name: spring-boot-app-2
  namespace: app2
spec:
  hosts:
  - "*"
  gateways:
  - ingress-gateway
  http:
    route:
    - destination:
        port:
          number: 8000