apiVersion: networking.istio.io/v1
kind: VirtualService
metadata:
  name: spring-boot-app-2
  namespace: app2
spec:
  hosts:
    - app2.demo.hu
  gateways:
    - istio-system/ingress-gateway
    - mesh
  http:
    - match:
        - uri:
            prefix: /
      route:
        - destination:
            host: spring-boot-app-2.app2.svc.cluster.local
            port:
              number: 8081