apiVersion: networking.istio.io/v1
kind: VirtualService
metadata:
  name: spring-boot-app-2
  namespace: app2
spec:
  hosts:
    - "*"
  gateways:
    - istio-system/ingress-gateway
  http:
    - match:
        - uri:
            prefix: /app2
      rewrite:
        uri: /
      route:
        - destination:
            host: spring-boot-app-2.app2.svc.cluster.local
            port:
              number: 8081