apiVersion: networking.istio.io/v1
kind: VirtualService
metadata:
  name: spring-boot-app
  namespace: app1
spec:
  hosts:
    - "*"
  gateways:
    - istio-system/ingress-gateway
  http:
    - match:
        - uri:
            prefix: /app1
      rewrite:
        uri: /
      route:
        - destination:
            host: spring-boot-app.app1.svc.cluster.local
            port:
              number: 8080